---
title: "Assignment 5"
author: "Liam Fruzyna"
output:
  pdf_document: default
  html_notebook: default
---

#### 2) Let ${y_t}$ represent the global temperature series (gtemp).
##### b) Fit the state-space model defined in a. Fit the smoother $x_t ^n$ with figure showing the gtemp plot, plot of the smooth gtemp and its 95% confidence interval.

```{r}
library(astsa)

# Model Setup
n= length(gtemp)
A=t(c(1, 0))
mu0=c(-0.26, -0.26)
Sigma0=diag(0.1, 2)
Phi=matrix(c(2, 1, -1, 0), 2)

# Likelihood Function
Likfn = function(para){
  cQ11=para[1]
  cR = para[2]
  cQ=matrix(c(cQ11,0, 0, 0), 2)
  kf = Kfilter0(n, gtemp, A, mu0, Sigma0, Phi, cQ, cR)
  return(kf$like) }

init.par = c(0.1, 0.1) # initial parameters
est = optim(init.par, Likfn, NULL, method = 'BFGS', hessian = TRUE, control=list(trace=1, REPORT=1))
SE = sqrt(diag(solve(est$hessian)))
estoutput = cbind(estimates=est$par, SE)
rownames(estoutput) = c('cQ11', 'cR')
estoutput
```

```{r}
# Smoothing
cQ11=est$par[1]; cR=est$par[2]
cQ=matrix(c(cQ11, 0, 0, 0), 2)
Q = t(cQ)%*%cQ
ks = Ksmooth0(n, gtemp, A, mu0, Sigma0, Phi, cQ, cR)
xsmooth = ts(as.vector(ks$xs[1,,]), start=1880)
p=2*sqrt(ks$Ps[1,1,])
plot(xsmooth, lty=1, main='Smoothed gtemp')
lines(xsmooth-p, col='red', lty=2)
lines(xsmooth+p, col='red', lty=2)
```