
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 22 12:16:19 CDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATTRIB = 45;
  public static final int SEP = 17;
  public static final int STRING_LITERAL = 54;
  public static final int LTE = 20;
  public static final int MULT = 8;
  public static final int PUT = 50;
  public static final int REQ = 41;
  public static final int SEMIC = 18;
  public static final int LPAREN = 10;
  public static final int INT = 2;
  public static final int ARRAY = 4;
  public static final int MINUS = 7;
  public static final int RPAREN = 11;
  public static final int IS = 37;
  public static final int NOT = 26;
  public static final int AND = 27;
  public static final int LT = 22;
  public static final int OR = 28;
  public static final int BANG = 16;
  public static final int BOOL = 3;
  public static final int CLASS = 43;
  public static final int DIV = 9;
  public static final int UNTIL = 35;
  public static final int UP = 53;
  public static final int LSB = 12;
  public static final int LOOP = 36;
  public static final int PLUS = 6;
  public static final int ASSIGN = 5;
  public static final int IF = 31;
  public static final int ID = 56;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int LOW = 52;
  public static final int METHOD = 44;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int NUMBER = 55;
  public static final int NEQ = 25;
  public static final int PUTSTR = 49;
  public static final int EQ = 24;
  public static final int GTE = 21;
  public static final int FROM = 34;
  public static final int COLON = 19;
  public static final int ELSE = 33;
  public static final int PUTINT = 48;
  public static final int RSB = 13;
  public static final int CREATE = 46;
  public static final int THEN = 32;
  public static final int END = 39;
  public static final int LOCAL = 40;
  public static final int MAKE = 47;
  public static final int AT = 15;
  public static final int ITEM = 51;
  public static final int FALSE = 30;
  public static final int GT = 23;
  public static final int DO = 38;
  public static final int ENSURE = 42;
}

